DROP TABLE MARKET_BOARD;

CREATE TABLE MARKET_BOARD(
	M_NAME VARCHAR2(4000),
	M_CODE VARCHAR2(4000),
	GUNAME VARCHAR2(4000),
	M_ADDR VARCHAR2(4000),
	LNG NUMBER,
	LAT NUMBER
);

SELECT * FROM MARKET_BOARD;

